stages:
  prepare:
    cmd: python src/prepare.py data/raw/aclImdb
    deps:
    - data/raw/aclImdb
    - src/prepare.py
    params:
    - prepare.seed
    - prepare.validation_split
    - prepare.batch_size
    outs:
    - data/prepared
  featurize:
    cmd: python src/featurize.py data/prepared data/features
    deps:
    - data/prepared
    - src/featurize.py
    params:
    - featurize.max_features
    - featurize.embedding_dim
    - featurize.sequence_length
    outs:
    - data/features
  train:
    cmd: python src/train.py data/features models
    deps:
    - data/features
    - src/train.py
    params:
      - train.epochs
      - train.model_dropout
      - train.model_kernel_size
      - train.model_strides
      - train.model_padding
    outs:
    - models/mlops-thesis-text-classification.onnx
  evaluate:
    cmd: python src/evaluate.py models/mlops-thesis-text-classification.onnx data/features
    deps:
    - data/features
    - models/mlops-thesis-text-classification.onnx
    - src/evaluate.py
    metrics:
    - src/metrics.json:
        cache: false
  #   plots:
  #   - evaluation/importance.png
  #   - evaluation/plots/confusion_matrix.json:
  #       cache: false
  #       template: confusion
  #       x: actual
  #       y: predicted
  #   - evaluation/plots/precision_recall.json:
  #       cache: false
  #       x: recall
  #       y: precision
  #   - evaluation/plots/roc.json:
  #       cache: false
  #       x: fpr
  #       y: tpr
