prepare:
  validation_split: 0.20
  seed: 20170428
  batch_size: 32

featurize:
  max_features: 20000
  embedding_dim: 128
  sequence_length: 500

train:
  epochs: 1
  model_dropout: 0.2
  model_kernel_size: 128
  model_strides: 3
  model_padding: 6

evaluate:
  metrics: src/metrics.json
