name: Train-on-Azure
on: 
  workflow_dispatch:
jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - name: Deploy runner on Azure VM
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          # AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          # AZURE_STORAGE_CONTAINER_NAME: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          CML_RUNNER_NAME: cml_runner_name
        run: |
          cml runner \
            --name cml_runner_name \
            --cloud=azure \
            --cloud-type=m \
            --cloud-region=eu-west \
            --labels=cml-runner \
            --cloud-permission-set=/subscriptions/5b6e9d1b-7336-4efc-80a9-a4970b5c5eb5/resourcegroups/RG-TERRAFORM-PROVISIONG/providers/Microsoft.ManagedIdentity/userAssignedIdentities/mlops-thesis-ghactions
  train-model:
    needs: deploy-runner
    runs-on: [self-hosted, cml-runner]
    timeout-minutes: 50400 # 35 days
    container:
      image: docker://dvcorg/cml
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # pip install -r requirements.txt
          # python train.py

          # cat metrics.txt > report.md
          # cml send-comment report.md
          echo "working"
